# Generated by Django 5.1.1 on 2024-09-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='ra',
            new_name='rA',
        ),
    ]
