# Generated by Django 5.1.1 on 2024-09-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_rename_ra_aluno_ra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='rA',
            new_name='ra',
        ),
    ]
