# Generated by Django 5.1.1 on 2024-09-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='capa_livro')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('editora_e_ano', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('data_emprestimo', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
