# Generated by Django 5.1.1 on 2024-09-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='data_devolucao',
            new_name='data_de_devolucao',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='data_emprestimo',
            new_name='data_de_emprestimo',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='editora_e_ano',
        ),
        migrations.AddField(
            model_name='livros',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='livros',
            name='editora_local_ano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alunos.prof'),
        ),
        migrations.AddField(
            model_name='livros',
            name='tombo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
