# Generated by Django 5.1.1 on 2024-09-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_rename_data_devolucao_livros_data_de_devolucao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='data_de_devolucao',
            new_name='data_de_devolução',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='data_de_emprestimo',
            new_name='data_de_empréstimo',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='editora_local_ano',
            new_name='local_Editora_Ano',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='observacao',
            new_name='observação',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='titulo',
            new_name='título',
        ),
    ]
