# Generated by Django 5.1.1 on 2024-09-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_rename_data_de_devolucao_livros_data_de_devolução_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_de_devolução',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_de_empréstimo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
