# Generated by Django 5.1.1 on 2024-09-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_livros_data_de_empréstimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_de_devolução',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_de_empréstimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
