# Generated by Django 5.1.1 on 2024-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_livros_data_de_devolução_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(blank=True, max_length=25, null=True)),
                ('planilha', models.FileField(upload_to='planilhas/')),
            ],
        ),
    ]
