# Generated by Django 5.1.1 on 2024-10-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_livros_tombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilha',
            name='arquivo',
            field=models.CharField(max_length=25),
        ),
    ]
