# Generated by Django 5.1.1 on 2024-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_alter_planilha_arquivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planilha',
        ),
    ]
