# Generated by Django 5.1.1 on 2024-10-05 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_rename_ra_aluno_ra'),
        ('livro', '0011_delete_planilha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos_Cadastrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_cadastrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alunos.aluno')),
            ],
        ),
    ]
