# Generated by Django 5.1.1 on 2024-10-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_alunos_cadastrados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alunos_Cadastrados',
        ),
    ]
