# Generated by Django 5.1.1 on 2024-10-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_delete_alunos_cadastrados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='img',
        ),
    ]
