# Generated by Django 5.1.1 on 2024-10-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_remove_livros_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='digital',
            field=models.FileField(blank=True, null=True, upload_to='livro_digital'),
        ),
    ]
